name: CI pipeline

on:
  push:
    branches:
      - dev
      - 'dev-*'

defaults:
  run:
    shell: bash

env:
  config: Debug

jobs:
  analyze:
    name: "Analyze (types: ${{matrix.types}}, concurrency: ${{matrix.concurrency}})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        types: [NORMAL, TINY, HUGE]
        concurrency: [OFF]
        include:
          - types: NORMAL
            concurrency: ON
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Pre-commit
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install pre-commit
          pre-commit run --from-ref=HEAD~1 --to-ref=HEAD

      - name: Configure
        run: >
          cmake --preset ci-analyze
          -DULIB_TYPES=${{matrix.types}}
          -DULIB_CONCURRENCY=${{matrix.concurrency}}

      - name: Build
        run: cmake --build --preset build

  test:
    name: "Test (os: ${{matrix.os}}, variant: ${{matrix.variant}})"
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        variant: [normal, tiny, huge, concurrency, platform-sync, shared-tsan, cpp]
        include:
          - lib_type: STATIC
            types: NORMAL
            concurrency: OFF
            platform_sync: OFF
            sanitizers: address;undefined
            cpp: OFF
          - variant: tiny
            types: TINY
          - variant: huge
            types: HUGE
          - variant: concurrency
            concurrency: ON
          - variant: platform-sync
            concurrency: ON
            platform_sync: ON
          - variant: shared-tsan
            lib_type: SHARED
            concurrency: ON
            sanitizers: thread
          - variant: cpp
            concurrency: ON
            cpp: ON
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure
        run: >
          cmake --preset ci-test
          -DCMAKE_BUILD_TYPE=${{env.config}}
          -DULIB_LIBRARY_TYPE=${{matrix.lib_type}}
          -DULIB_TYPES=${{matrix.types}}
          -DULIB_CONCURRENCY=${{matrix.concurrency}}
          -DULIB_PLATFORM_SYNC=${{matrix.platform_sync}}
          -DULIB_SANITIZERS="${{matrix.sanitizers}}"
          -DULIB_CPP_TESTS=${{matrix.cpp}}

      - name: Build
        run: cmake --build --preset build --config ${{env.config}}

      - name: Prepare workdir (Windows)
        working-directory: build
        if: runner.os == 'Windows'
        run: |
          if [ ${{matrix.lib_type}} == 'SHARED' ]; then
            for exe_dir in test bench; do
              cp ${{env.config}}/*.dll ${exe_dir}/${{env.config}}
            done
          fi

      - name: Run
        run: ctest --preset test --build-config ${{env.config}}

  bench:
    name: "Benchmark (os: ${{matrix.os}})"
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure
        run: cmake -B build --preset bench -DCMAKE_BUILD_TYPE=${{env.config}}

      - name: Build
        run: cmake --build --preset build --config ${{env.config}}

      - name: Run
        run: ctest --preset bench --build-config ${{env.config}}

  docs:
    name: Documentation
    runs-on: ubuntu-26.04 # Revert to ubuntu-latest when it is updated to 26.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt install doxygen
          python -m venv .venv
          source .venv/bin/activate
          pip install Sphinx sphinx-rtd-theme breathe

      - name: Build
        run: |
          source .venv/bin/activate
          cmake --preset docs
          cmake --build --preset docs
