name: CI pipeline

on:
  push:
    branches:
      - dev
      - 'dev-*'

defaults:
  run:
    shell: bash

env:
  config: Release

jobs:
  analyze:
    name: "Analyze (types: ${{matrix.types}}, concurrency: ${{matrix.concurrency}})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        types: [normal, tiny, huge]
        concurrency: [off]
        include:
          - types: normal
            concurrency: on
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Pre-commit
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install pre-commit
          pre-commit run --from-ref=HEAD~1 --to-ref=HEAD

      - name: Configure
        run: >
          cmake --preset ci-analyze
          -DULIB_TINY=${{matrix.types == 'tiny' && 'ON' || 'OFF'}}
          -DULIB_HUGE=${{matrix.types == 'huge' && 'ON' || 'OFF'}}
          -DULIB_CONCURRENCY=${{matrix.concurrency == 'on' && 'ON' || 'OFF'}}

      - name: Build
        run: cmake --build --preset build

  test:
    name: "Test (os: ${{matrix.os}}, lib_type: ${{matrix.lib_type}}, types: ${{matrix.types}}, concurrency: ${{matrix.concurrency}})"
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        lib_type: [STATIC]
        types: [normal, tiny, huge]
        concurrency: [off]
        include:
          - os: ubuntu
            lib_type: SHARED
            types: normal
            concurrency: on
          - os: windows
            lib_type: SHARED
            types: normal
            concurrency: on
          - os: macos
            lib_type: SHARED
            types: normal
            concurrency: on
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure
        run: >
          cmake --preset ci-test
          -DCMAKE_BUILD_TYPE=${{env.config}}
          -DULIB_LIBRARY_TYPE=${{matrix.lib_type}}
          -DULIB_TINY=${{matrix.types == 'tiny' && 'ON' || 'OFF'}}
          -DULIB_HUGE=${{matrix.types == 'huge' && 'ON' || 'OFF'}}
          -DULIB_CONCURRENCY=${{matrix.concurrency == 'on' && 'ON' || 'OFF'}}

      - name: Build
        run: cmake --build --preset build --config ${{env.config}}

      - name: Prepare workdir (Windows)
        working-directory: build
        if: runner.os == 'Windows'
        run: |
          if [ ${{matrix.lib_type}} == 'SHARED' ]; then
            for exe_dir in test bench; do
              cp ${{env.config}}/*.dll ${exe_dir}/${{env.config}}
            done
          fi

      - name: Run
        run: ctest --preset test --build-config ${{env.config}}

  bench:
    name: "Benchmark (os: ${{matrix.os}})"
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure
        run: cmake -B build --preset bench -DCMAKE_BUILD_TYPE=${{env.config}}

      - name: Build
        run: cmake --build --preset build --config ${{env.config}}

      - name: Run
        run: ctest --preset bench --build-config ${{env.config}}

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt install doxygen
          python -m venv .venv
          source .venv/bin/activate
          pip install Sphinx sphinx-rtd-theme breathe

      - name: Build
        run: |
          source .venv/bin/activate
          cmake --preset docs
          cmake --build --preset docs
